
package Vista;

import Controlador.ModeloCarroController;
import Modelo.TBLMarcaVo;
import Modelo.TBLTipoCombustibleVo;
import Modelo.impl.DropBoxImpl;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.TableCellRenderer;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import jdk.internal.org.jline.terminal.spi.JansiSupport;

/**
 *
 * @author Elias ,Daniel
 */
public class FrmCrearModeloCarrro extends javax.swing.JFrame {

    /**
     * Creates new form FrmCrearModeloCarrro
     */
    public String Ruta = "";
    
    private static ModeloCarroController model;
    private TBLMarcaVo marcas;
    private DropBoxImpl dropBoxImpl;
    private int id;
    DefaultTableModel modelo;

    public FrmCrearModeloCarrro(TBLMarcaVo marcas) {
        model = new ModeloCarroController();
        dropBoxImpl = new DropBoxImpl();
        initComponents();
        setTitle("Modelo");
        model.loadData(tbGetDatosModelo, "");
        this.marcas = marcas;
        this.listAno(0);
        this.ltsTipoCombustible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbGrupoEliminar_Actualizar = new javax.swing.ButtonGroup();
        FramImagen = new javax.swing.JFrame();
        Labelimagenes = new javax.swing.JLabel();
        jpanelModeloCarro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCilindraje = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnGuardarModelo = new javax.swing.JButton();
        ExaminarImagen = new javax.swing.JButton();
        btnActualizarModelo = new javax.swing.JButton();
        btnEliminarModelo = new javax.swing.JButton();
        imgProducto = new javax.swing.JLabel();
        btnLimpiarCampos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGetDatosModelo = new javax.swing.JTable();
        txtFilterTable = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelIdRegistro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ListTipoCombistible = new javax.swing.JComboBox<>();
        labelRutaImagen = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        listAnio = new javax.swing.JComboBox<>();
        BotonBuscarModelo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout FramImagenLayout = new javax.swing.GroupLayout(FramImagen.getContentPane());
        FramImagen.getContentPane().setLayout(FramImagenLayout);
        FramImagenLayout.setHorizontalGroup(
            FramImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramImagenLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Labelimagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        FramImagenLayout.setVerticalGroup(
            FramImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramImagenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Labelimagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jpanelModeloCarro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("Descripción");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Imagen");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Cilindraje");

        txtCilindraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCilindrajeActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescripcionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescripcion);
        txtDescripcion.getAccessibleContext().setAccessibleParent(this);

        btnGuardarModelo.setBackground(new java.awt.Color(209, 37, 29));
        btnGuardarModelo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnGuardarModelo.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarModelo.setText("Crear Modelo");
        btnGuardarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModeloActionPerformed(evt);
            }
        });

        ExaminarImagen.setBackground(new java.awt.Color(209, 37, 29));
        ExaminarImagen.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ExaminarImagen.setForeground(new java.awt.Color(255, 255, 255));
        ExaminarImagen.setText("Examinar Imagen");
        ExaminarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminarImagenActionPerformed(evt);
            }
        });

        btnActualizarModelo.setBackground(new java.awt.Color(209, 37, 29));
        btnActualizarModelo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnActualizarModelo.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarModelo.setText("Actualizar Modelo");
        btnActualizarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarModeloActionPerformed(evt);
            }
        });

        btnEliminarModelo.setBackground(new java.awt.Color(209, 37, 29));
        btnEliminarModelo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnEliminarModelo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarModelo.setText("Eliminar Modelo");
        btnEliminarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarModeloActionPerformed(evt);
            }
        });

        imgProducto.setBackground(new java.awt.Color(255, 255, 255));

        btnLimpiarCampos.setBackground(new java.awt.Color(209, 37, 29));
        btnLimpiarCampos.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnLimpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        tbGetDatosModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbGetDatosModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGetDatosModeloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbGetDatosModeloMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbGetDatosModelo);
        if (tbGetDatosModelo.getColumnModel().getColumnCount() > 0) {
            tbGetDatosModelo.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tbGetDatosModelo.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tbGetDatosModelo.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tbGetDatosModelo.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        txtFilterTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterTableActionPerformed(evt);
            }
        });
        txtFilterTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterTableKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Filtro");

        labelIdRegistro.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setText("Tipo de Combustible");

        ListTipoCombistible.setBackground(new java.awt.Color(209, 37, 29));
        ListTipoCombistible.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ListTipoCombistible.setForeground(new java.awt.Color(255, 255, 255));
        ListTipoCombistible.setName(""); // NOI18N
        ListTipoCombistible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTipoCombistibleActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel10.setText("Año");

        listAnio.setBackground(new java.awt.Color(209, 37, 29));
        listAnio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listAnio.setForeground(new java.awt.Color(255, 255, 255));
        listAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAnioActionPerformed(evt);
            }
        });

        BotonBuscarModelo.setBackground(new java.awt.Color(209, 37, 29));
        BotonBuscarModelo.setForeground(new java.awt.Color(255, 255, 255));
        BotonBuscarModelo.setText("Buscar");
        BotonBuscarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelModeloCarroLayout = new javax.swing.GroupLayout(jpanelModeloCarro);
        jpanelModeloCarro.setLayout(jpanelModeloCarroLayout);
        jpanelModeloCarroLayout.setHorizontalGroup(
            jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                        .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(ListTipoCombistible, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10)
                                .addGap(21, 21, 21)
                                .addComponent(listAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8)
                                .addComponent(ExaminarImagen)
                                .addGap(36, 36, 36)
                                .addComponent(labelRutaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFilterTable, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonBuscarModelo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEliminarModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardarModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnActualizarModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                        .addGap(722, 722, 722)
                        .addComponent(labelIdRegistro)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpanelModeloCarroLayout.setVerticalGroup(
            jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ListTipoCombistible, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(listAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelRutaImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ExaminarImagen))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelIdRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFilterTable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotonBuscarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18))
                    .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnGuardarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );

        txtNombre.getAccessibleContext().setAccessibleParent(this);
        txtCilindraje.getAccessibleContext().setAccessibleParent(this);
        btnGuardarModelo.getAccessibleContext().setAccessibleParent(this);

        jLabel6.setBackground(new java.awt.Color(204, 204, 0));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 37, 29));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FORMULARIO PARA GESTIONAR MODELO DE lAS MARCAS");
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setDoubleBuffered(true);
        jLabel6.setFocusCycleRoot(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpanelModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txtFilterTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterTableKeyReleased
        
    }//GEN-LAST:event_txtFilterTableKeyReleased

    private void tbGetDatosModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGetDatosModeloMouseClicked
        modificar();
        
    }//GEN-LAST:event_tbGetDatosModeloMouseClicked
    private void cargarImagen(){
        String urlImagen = "/AutopartesLeon/modelo/DCBR_NISSAN.jpg";
        ImageIcon icon = new ImageIcon(urlImagen);
        //this.lbFondo.setIcon(icon);
        //this.lbFondo.setText("");
  }
    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        txtNombre.setText("");
         txtCilindraje.setText("");
         txtDescripcion.setText("");
         imgProducto.setIcon(null);
         labelRutaImagen.setText("");
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed
  private void limpiarCampos(){
         txtNombre.setText("");
         txtCilindraje.setText("");
         txtDescripcion.setText("");
         imgProducto.setIcon(null);
         labelRutaImagen.setText("");
    }
  
    private void btnEliminarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarModeloActionPerformed
           if (!labelIdRegistro.getText().isEmpty()) {
                if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this,
                        "¿Esta seguro de que desea borrar este modelo?", "Pregunta", JOptionPane.YES_NO_OPTION)) {
                   try {
                       model.deleteModelo(labelIdRegistro.getText());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Ocurrio un error al eliminar un modelo", JOptionPane.ERROR_MESSAGE);
                    }             
                   JOptionPane.showMessageDialog(null,"Modelo eliminado correctamente", "Modelo Eliminado",JOptionPane.INFORMATION_MESSAGE);
                }
                    model.loadData(tbGetDatosModelo,"");
            }else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un modelo para eliminar", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarModeloActionPerformed

    private void btnActualizarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarModeloActionPerformed
        TBLTipoCombustibleVo tipoCombustible = (TBLTipoCombustibleVo) ListTipoCombistible.getSelectedItem();
        String anio = (String) listAnio.getSelectedItem();
        if (!labelIdRegistro.getText().isEmpty()) {
            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this,
                    "¿Esta seguro de que desea actualizar este modelo?", "Pregunta", JOptionPane.YES_NO_OPTION)) {
                try {
                    String path = Ruta;
                    if (!Ruta.contains("/AutopartesLeon/")) {
                        path = dropBoxImpl.uploadFIleDropbox("modelo", Ruta);
                    }

                    model.updateModel(Integer.parseInt(labelIdRegistro.getText()), txtNombre.getText(), anio, txtCilindraje.getText(), tipoCombustible, txtDescripcion.getText(), path, marcas);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Ocurrio un error al actualizar un modelo", JOptionPane.ERROR_MESSAGE);
                }
                JOptionPane.showMessageDialog(this, "Modelo actualizado correctamente", "Modelo Actualizado", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un modelo para actualizar", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        model.loadData(tbGetDatosModelo, "");
        limpiarCampos();

    }//GEN-LAST:event_btnActualizarModeloActionPerformed

    private void ExaminarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminarImagenActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        jFileChooser.setFileFilter(fileNameExtensionFilter);

        if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Ruta = jFileChooser.getSelectedFile().getAbsolutePath();
            Image mImagen = new ImageIcon(Ruta).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(this.imgProducto.getWidth(), this.imgProducto.getHeight(), Image.SCALE_SMOOTH));
            imgProducto.setIcon(mIcono);
        }
        labelRutaImagen.setText(splitPAthImg(Ruta));
    }//GEN-LAST:event_ExaminarImagenActionPerformed

    private void btnGuardarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModeloActionPerformed
        TBLTipoCombustibleVo tipoCombustible = (TBLTipoCombustibleVo)ListTipoCombistible.getSelectedItem();      
        String anio = (String) listAnio.getSelectedItem();
        if(modeloEsValido(txtNombre.getText(), txtCilindraje.getText(),tipoCombustible.getNombre(),anio, labelRutaImagen.getText(),txtDescripcion.getText())){
            String path = dropBoxImpl.uploadFIleDropbox("modelo", Ruta);
            model.save(txtNombre.getText(),anio,txtCilindraje.getText(),tipoCombustible, txtDescripcion.getText(), path,marcas);
            model.loadData(tbGetDatosModelo,"");
            
        JOptionPane.showMessageDialog(null,"Modelo creaco correctamente", "Modelo creado",JOptionPane.INFORMATION_MESSAGE); 
        limpiarCampos();
        }else {
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_btnGuardarModeloActionPerformed
     public boolean modeloEsValido(String nombre , String cilindraje  , String tipoCombstible, String anio ,String rutaImagen, String descripcion) {
        return !nombre.isEmpty() && !cilindraje.isEmpty() && !tipoCombstible.isEmpty()  && !anio.isEmpty() && !rutaImagen.isEmpty() && !descripcion.isEmpty();
    }
    private void txtDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionMouseClicked

    }//GEN-LAST:event_txtDescripcionMouseClicked

    private void txtCilindrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCilindrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCilindrajeActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void listEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listEstadoActionPerformed

    private void ListTipoCombistibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTipoCombistibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTipoCombistibleActionPerformed

    private void txtFilterTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterTableActionPerformed

    private void listAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listAnioActionPerformed

    private void BotonBuscarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarModeloActionPerformed
        // TODO add your handling code here:
        
        model.loadData(tbGetDatosModelo, txtFilterTable.getText());
    }//GEN-LAST:event_BotonBuscarModeloActionPerformed

 
    private void tbGetDatosModeloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGetDatosModeloMousePressed
        FramImagen.setVisible(true);
       FramImagen.setSize(500, 500);
  
         int fila =tbGetDatosModelo.getSelectedRow();
         Ruta = tbGetDatosModelo.getValueAt(fila, 3).toString();  
         //ImageIcon imagen = new ImageIcon("Imagenes\fondo.PNG");
         Image img= new ImageIcon("C:/Users/Admin/Desktop/app taller/stanalone_app_repuestos/Sistema-De-Inventarios-master/src/Imagenes/icondaihatsu.png").getImage();
         ImageIcon img2=new ImageIcon(img.getScaledInstance(78, 124, Image.SCALE_SMOOTH));

          Labelimagenes.setIcon(img2);   
         //FramImagen.add(Labelimagenes);
      
   
	//FramImagen.setLocationRelativeTo(null);
        System.out.println("frame pressed");
        System.out.println("dialog focused ");
        System.out.println("frame focused ");
       
    }//GEN-LAST:event_tbGetDatosModeloMousePressed

    
        private byte[] getImagen(String ruta) {
        File imagen = new File(ruta);
        try {
            byte[] icono = new byte[(int) imagen.length()];
            InputStream inputStream = new FileInputStream(imagen);
            inputStream.read(icono);
            return icono;

        } catch (Exception e) {
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearModeloCarrro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearModeloCarrro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearModeloCarrro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearModeloCarrro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearModeloCarrro(new TBLMarcaVo()).setVisible(true);
            }
        });
    }
    
   public void modificar(){
     int fila =tbGetDatosModelo.getSelectedRow();
     String anio = (String) listAnio.getSelectedItem();
     if(fila >=0){      
       Ruta="";
       txtNombre.setText(tbGetDatosModelo.getValueAt(fila, 1).toString());
       txtDescripcion.setText(tbGetDatosModelo.getValueAt(fila, 2).toString());
        Ruta = tbGetDatosModelo.getValueAt(fila, 3).toString();
       labelRutaImagen.setText(splitPAthImg(Ruta));
       this.ltsTipoCombustible();
       txtCilindraje.setText(tbGetDatosModelo.getValueAt(fila, 5).toString());     
       this.listAno(Integer.parseInt(anio));
       //marcas
       labelIdRegistro.setText(tbGetDatosModelo.getValueAt(fila, 8).toString());
       
       //imagen
        String img = dropBoxImpl.getFileDrobox(Ruta);
        Image mImagen = new ImageIcon(img).getImage();
        ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(this.imgProducto.getWidth(), this.imgProducto.getHeight(), Image.SCALE_SMOOTH));
        imgProducto.setIcon(mIcono);
            

     }
 } 
 public void listDias(int dia){
  for(int i=1; i<=31;i++){
    if(dia != i){
     //listDia.addItem(String.valueOf(i));
    }
  }
 }
 public void listMes(String mesP){
 String meses[] = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
  for(String mes: meses)
      if(!mesP.equals(mes)){
//          ListMes.addItem(mes);
      }
    }
 public void listAno(int ano){     
     for(int i=1900;i<=3000;i++){
       if(ano != i){
       listAnio.addItem(String.valueOf(i));
       }
       
     }
 }
 public void ltsTipoCombustible(){
     model.ltsTipoCombustible().forEach(obj->{
        ListTipoCombistible.addItem(obj);
     });
 }  
    public void ltsMarca(){
     model.ltsMarca().forEach(obj->{
        //ListMarca.addItem(obj);
     });
 }
 public String splitPAthImg(String pathImg){
       pathImg = pathImg.replace("\\", "1000001").replace("/", "1000001");
            String spl[] = pathImg.split("1000001");
            int cont = 0;
            for(String st: spl){
                cont +=1;
            }
            return spl[cont-1];
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarModelo;
    private javax.swing.JButton ExaminarImagen;
    private javax.swing.JFrame FramImagen;
    private javax.swing.JLabel Labelimagenes;
    private javax.swing.JComboBox<TBLTipoCombustibleVo> ListTipoCombistible;
    public javax.swing.JButton btnActualizarModelo;
    public javax.swing.JButton btnEliminarModelo;
    public javax.swing.JButton btnGuardarModelo;
    public javax.swing.JButton btnLimpiarCampos;
    public javax.swing.JLabel imgProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanelModeloCarro;
    public javax.swing.JLabel labelIdRegistro;
    private javax.swing.JLabel labelRutaImagen;
    private javax.swing.JComboBox<String> listAnio;
    private javax.swing.ButtonGroup rdbGrupoEliminar_Actualizar;
    public javax.swing.JTable tbGetDatosModelo;
    public javax.swing.JTextField txtCilindraje;
    public javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFilterTable;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

   
}
