
package Vista;

import Controlador.ModeloRepuestoCarroController;
import Controlador.RepuestoCarroController;
import Controlador.RepuestoXModeloController;
import Modelo.TBLMarcaVo;
import Modelo.TBLModeloXRepuestoVo;
import Modelo.TBLTipoCombustibleVo;
import Modelo.impl.DropBoxImpl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import util.MarcasCarros;

/**
 *
 * @author Elias ,Daniel
 */
public class FrmListarModelosxRepuestos extends javax.swing.JFrame {

    /**
     * Creates new form FrmCrearModeloCarrro
     */
    public String Ruta = "";
    
    private static ModeloRepuestoCarroController model;
    private TBLMarcaVo marcas;
    private DropBoxImpl dropBoxImpl;
    private RepuestoCarroController controlRepuesto;
    private int idModelo;
    DefaultTableModel modelo;
    private static RepuestoCarroController repuesto;
    
    
    private RepuestoXModeloController control;
    
    public FrmListarModelosxRepuestos(TBLMarcaVo marcas) {
        repuesto = new RepuestoCarroController();
        model = new ModeloRepuestoCarroController();
        dropBoxImpl = new DropBoxImpl();
        control = new RepuestoXModeloController();
        initComponents();
        this.controlRepuesto = new RepuestoCarroController();
        setTitle("Autopartes Leon");
        
        this.getContentPane().setBackground(Color.WHITE);
         getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
         //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.marcas = marcas;
        jLabel6.setText(" LISTA  MODELOS Y REPUESTOS DE "+this.marcas.getNombre().toUpperCase());
        
        imgProducto.setFont(new Font("Serief", Font.ITALIC, 35));
        //==========
        setIconImage(new ImageIcon(dropBoxImpl.getFileDrobox("/AutopartesLeon/recusos_app/logoAutopartes.PNG")).getImage());
        control.loadDataAllModeloXRepuesto(tbrepuestoxmodelo, "", marcas.getIdMarca(), "");
        iconDefault();
        
        jLabel7.setVisible(false);
        txtFilterTable1.setVisible(false);
        BotonFiltrarRepuesto.setVisible(false);
        tbGetDatosRepuesto.setVisible(false);
        jScrollPane3.setVisible(false);
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbGrupoEliminar_Actualizar = new javax.swing.ButtonGroup();
        FramImagen = new javax.swing.JFrame();
        Labelimagenes = new javax.swing.JLabel();
        jpanelModeloCarro = new javax.swing.JPanel();
        imgProducto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbrepuestoxmodelo = new javax.swing.JTable();
        BotonFiltrar = new javax.swing.JButton();
        txtFilterTable = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbGetDatosRepuesto = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtFilterTable1 = new javax.swing.JTextField();
        BotonFiltrarRepuesto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout FramImagenLayout = new javax.swing.GroupLayout(FramImagen.getContentPane());
        FramImagen.getContentPane().setLayout(FramImagenLayout);
        FramImagenLayout.setHorizontalGroup(
            FramImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FramImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Labelimagenes, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        FramImagenLayout.setVerticalGroup(
            FramImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FramImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Labelimagenes, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jpanelModeloCarro.setBackground(new java.awt.Color(255, 255, 255));

        imgProducto.setBackground(new java.awt.Color(255, 255, 255));

        tbrepuestoxmodelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrepuestoxmodelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbrepuestoxmodelo.setRowHeight(30);
        tbrepuestoxmodelo.setRowMargin(10);
        tbrepuestoxmodelo.setSelectionBackground(new java.awt.Color(102, 204, 255));
        tbrepuestoxmodelo.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbrepuestoxmodelo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbrepuestoxmodeloAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbrepuestoxmodelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbrepuestoxmodeloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbrepuestoxmodeloMousePressed(evt);
            }
        });
        tbrepuestoxmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbrepuestoxmodeloKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbrepuestoxmodelo);

        BotonFiltrar.setBackground(new java.awt.Color(209, 37, 29));
        BotonFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonFiltrar.setText("Buscar");
        BotonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFiltrarActionPerformed(evt);
            }
        });

        txtFilterTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Filtro");

        jLabel10.setBackground(new java.awt.Color(204, 204, 0));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(209, 37, 29));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.setDoubleBuffered(true);
        jLabel10.setFocusCycleRoot(true);

        tbGetDatosRepuesto.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        tbGetDatosRepuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGetDatosRepuesto.setRowHeight(30);
        tbGetDatosRepuesto.setRowMargin(10);
        tbGetDatosRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGetDatosRepuestoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbGetDatosRepuestoMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbGetDatosRepuesto);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Filtro");

        txtFilterTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterTable1KeyReleased(evt);
            }
        });

        BotonFiltrarRepuesto.setBackground(new java.awt.Color(209, 37, 29));
        BotonFiltrarRepuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonFiltrarRepuesto.setForeground(new java.awt.Color(255, 255, 255));
        BotonFiltrarRepuesto.setText("Buscar");
        BotonFiltrarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFiltrarRepuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelModeloCarroLayout = new javax.swing.GroupLayout(jpanelModeloCarro);
        jpanelModeloCarro.setLayout(jpanelModeloCarroLayout);
        jpanelModeloCarroLayout.setHorizontalGroup(
            jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelModeloCarroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelModeloCarroLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelModeloCarroLayout.createSequentialGroup()
                        .addComponent(imgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(449, 449, 449))))
            .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelModeloCarroLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFilterTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonFiltrarRepuesto)
                        .addGap(1183, 1183, 1183))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFilterTable, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonFiltrar)
                        .addGap(1193, 1193, 1193))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jpanelModeloCarroLayout.setVerticalGroup(
            jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                .addComponent(imgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanelModeloCarroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtFilterTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jpanelModeloCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFilterTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonFiltrarRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(204, 204, 0));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 37, 29));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" LISTA  MODELOS Y REPUESTOS ");
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setDoubleBuffered(true);
        jLabel6.setFocusCycleRoot(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpanelModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanelModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listEstadoActionPerformed

    private void tbrepuestoxmodeloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbrepuestoxmodeloMousePressed

    }//GEN-LAST:event_tbrepuestoxmodeloMousePressed

    private void tbrepuestoxmodeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbrepuestoxmodeloMouseClicked
       int fila = tbrepuestoxmodelo.rowAtPoint(evt.getPoint());
        int colunm = tbrepuestoxmodelo.getColumnModel().getColumnIndexAtX(evt.getX());
        if (fila >= 0) {
            idModelo = Integer.parseInt(tbrepuestoxmodelo.getValueAt(fila, 8).toString());
           control.loadDataModeloRepuesto(tbGetDatosRepuesto, "",idModelo );
        jLabel7.setVisible(true);
        txtFilterTable1.setVisible(true);
        BotonFiltrarRepuesto.setVisible(true);
        tbGetDatosRepuesto.setVisible(true);
        jScrollPane3.setVisible(true); 
        }
         Object value = tbrepuestoxmodelo.getValueAt(fila, colunm);
         if (value instanceof JButton) {
            ((JButton) value).doClick();
            JButton btn = (JButton) value;
             if (btn.getName().equals("id_btn_ver_rep_img")) {

                Ruta = tbrepuestoxmodelo.getValueAt(fila, 6).toString();
                String imagen = dropBoxImpl.getFileDrobox(Ruta);
                Image img3 = new ImageIcon(imagen).getImage();
                Dimension size = new Dimension(img3.getWidth(null), img3.getHeight(null));
                ImageIcon img2 = new ImageIcon(img3);

                FramImagen.getContentPane().setLayout(new BorderLayout());

                Labelimagenes.setIcon(img2);
                FramImagen.getContentPane().add(Labelimagenes, BorderLayout.CENTER);

                FramImagen.getContentPane().setBackground(Color.WHITE);
                FramImagen.setSize(new Dimension(img3.getWidth(this) + 50, img3.getWidth(this) + 50));
                FramImagen.setIconImage(new ImageIcon(dropBoxImpl.getFileDrobox("/AutopartesLeon/recusos_app/logoAutopartes.PNG")).getImage());
                FramImagen.getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(209, 37, 29)));
                FramImagen.setVisible(true);
                FramImagen.setLocationRelativeTo(null);
                FramImagen.setResizable(false);
            }
         }
    }//GEN-LAST:event_tbrepuestoxmodeloMouseClicked

    private void BotonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFiltrarActionPerformed
         control.loadDataAllModeloXRepuesto(tbrepuestoxmodelo, txtFilterTable.getText(), marcas.getIdMarca(), "");
    }//GEN-LAST:event_BotonFiltrarActionPerformed

    private void tbrepuestoxmodeloAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbrepuestoxmodeloAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbrepuestoxmodeloAncestorAdded

    private void tbGetDatosRepuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGetDatosRepuestoMouseClicked
        int fila = tbGetDatosRepuesto.rowAtPoint(evt.getPoint());
        int colunm = tbGetDatosRepuesto.getColumnModel().getColumnIndexAtX(evt.getX());
                Object value = tbGetDatosRepuesto.getValueAt(fila, colunm);
        if (value instanceof JButton) {
            ((JButton) value).doClick();
            JButton btn = (JButton) value;
             if (btn.getName().equals("elimnar_btn")) {
                if(control.delete(Integer.parseInt(tbGetDatosRepuesto.getValueAt(fila, 8).toString()))){
                JOptionPane.showMessageDialog(null, "Registro Eliminado Exitoso", "Registro Eliminado Exitoso", JOptionPane.INFORMATION_MESSAGE);
                control.loadDataAllModeloXRepuesto(tbGetDatosRepuesto, "", marcas.getIdMarca(), "Eliminado");
                };
            }else if (btn.getName().equals("id_visualizar")) {

                Ruta = tbGetDatosRepuesto.getValueAt(fila, 3).toString();
                String imagen = dropBoxImpl.getFileDrobox(Ruta);
                Image img3 = new ImageIcon(imagen).getImage();
                Dimension size = new Dimension(img3.getWidth(null), img3.getHeight(null));
                ImageIcon img2 = new ImageIcon(img3);

                FramImagen.getContentPane().setLayout(new BorderLayout());

                Labelimagenes.setIcon(img2);
                FramImagen.getContentPane().add(Labelimagenes, BorderLayout.CENTER);

                FramImagen.getContentPane().setBackground(Color.WHITE);
                FramImagen.setSize(new Dimension(img3.getWidth(this) + 50, img3.getWidth(this) + 50));
                FramImagen.setIconImage(new ImageIcon(dropBoxImpl.getFileDrobox("/AutopartesLeon/recusos_app/logoAutopartes.PNG")).getImage());
                FramImagen.getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(209, 37, 29)));
                FramImagen.setVisible(true);
                FramImagen.setLocationRelativeTo(null);
                FramImagen.setResizable(false);
            }
        }
    }//GEN-LAST:event_tbGetDatosRepuestoMouseClicked

    private void tbGetDatosRepuestoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGetDatosRepuestoMousePressed

    }//GEN-LAST:event_tbGetDatosRepuestoMousePressed

    private void txtFilterTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterTable1KeyReleased

    }//GEN-LAST:event_txtFilterTable1KeyReleased

    private void BotonFiltrarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFiltrarRepuestoActionPerformed
        control.loadDataModeloRepuesto(tbGetDatosRepuesto, txtFilterTable1.getText(), idModelo);
    }//GEN-LAST:event_BotonFiltrarRepuestoActionPerformed

    private void tbrepuestoxmodeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbrepuestoxmodeloKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbrepuestoxmodeloKeyReleased

 
    
        private byte[] getImagen(String ruta) {
        File imagen = new File(ruta);
        try {
            byte[] icono = new byte[(int) imagen.length()];
            InputStream inputStream = new FileInputStream(imagen);
            inputStream.read(icono);
            return icono;

        } catch (Exception e) {
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListarModelosxRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListarModelosxRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListarModelosxRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListarModelosxRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListarModelosxRepuestos(new TBLMarcaVo()).setVisible(true);
            }
        });
    }
    

 public String splitPAthImg(String pathImg){
       pathImg = pathImg.replace("\\", "1000001").replace("/", "1000001");
            String spl[] = pathImg.split("1000001");
            int cont = 0;
            for(String st: spl){
                cont +=1;
            }
            return spl[cont-1];
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonFiltrar;
    private javax.swing.JButton BotonFiltrarRepuesto;
    private javax.swing.JFrame FramImagen;
    private javax.swing.JLabel Labelimagenes;
    public javax.swing.JLabel imgProducto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpanelModeloCarro;
    private javax.swing.ButtonGroup rdbGrupoEliminar_Actualizar;
    public javax.swing.JTable tbGetDatosRepuesto;
    private javax.swing.JTable tbrepuestoxmodelo;
    private javax.swing.JTextField txtFilterTable;
    private javax.swing.JTextField txtFilterTable1;
    // End of variables declaration//GEN-END:variables

       private void iconDefault() {
        if(marcas.getIdMarca() == MarcasCarros.TOYOTA.getId()){
            imgProducto.setIcon(new ImageIcon(dropBoxImpl.getFileDrobox("/AutopartesLeon/recusos_app/toyotaIcon.gif")));
        }else if(marcas.getIdMarca() == MarcasCarros.MITSUBISHI.getId()){
            imgProducto.setIcon(new ImageIcon(dropBoxImpl.getFileDrobox("/AutopartesLeon/recusos_app/mitsubishiIcon.gif")));
        }else if(marcas.getIdMarca() == MarcasCarros.NISSAN.getId()){
            imgProducto.setIcon(new ImageIcon(dropBoxImpl.getFileDrobox("/AutopartesLeon/recusos_app/nissanIcon.gif")));
        }else if(marcas.getIdMarca() == MarcasCarros.DAIHATSU.getId()){
            imgProducto.setIcon(new ImageIcon(dropBoxImpl.getFileDrobox("/AutopartesLeon/recusos_app/daihatsuIcon.gif")));
        }
    }
}
