/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Controlador.PrincipalController;
import Modelo.TBLMarcaVo;
import Modelo.impl.DropBoxImpl;
import Modelo.impl.TBLMarcaImpl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import util.FRMJFrame;
import util.LoadingThread;
import util.MarcasCarros;


/**
 *
 * @author ialonzo
 */
public class FrmPrincipal extends javax.swing.JFrame {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
        PanelImage fondo = new PanelImage();
        PrincipalController controller;
       private DropBoxImpl dropBoxImpl;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        dropBoxImpl = new DropBoxImpl();
        // cargas listas
        controller = new PrincipalController();
       
        this.setContentPane(fondo);
        initComponents();
        setTitle("BIENVENIDOS A REPUESTOS AUTOPARTES LEON");
        Toolkit toolkit=Toolkit.getDefaultToolkit();
        Image icon = toolkit.getImage(dropBoxImpl.getFileDrobox("/AutopartesLeon/recusos_app/logoAutopartes.PNG"));
        setIconImage(icon);
        
       
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        BotonMitsubitshi = new javax.swing.JButton();
        BotonToyota = new javax.swing.JButton();
        BotonDihatsu = new javax.swing.JButton();
        gestionarModelosToyotaBoton = new javax.swing.JButton();
        BotonNissan = new javax.swing.JButton();
        gestionarModelosMitsubishiBoton = new javax.swing.JButton();
        gestionarModelosDaihatsuBoton = new javax.swing.JButton();
        modeloXRepuestoBoton = new javax.swing.JButton();
        gestionarModelosNissanBoton = new javax.swing.JButton();
        gestionarRepuestosBoton = new javax.swing.JButton();
        jPanel1 = new PanelImageLogo();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuSalir = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BotonMitsubitshi.setBackground(new java.awt.Color(255, 255, 255));
        BotonMitsubitshi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconmitsubishi.png"))); // NOI18N
        BotonMitsubitshi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMitsubitshiActionPerformed(evt);
            }
        });

        BotonToyota.setBackground(new java.awt.Color(255, 255, 255));
        BotonToyota.setForeground(new java.awt.Color(255, 255, 255));
        BotonToyota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icontoyota.png"))); // NOI18N
        BotonToyota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonToyotaActionPerformed(evt);
            }
        });

        BotonDihatsu.setBackground(new java.awt.Color(255, 255, 255));
        BotonDihatsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icondaihatsu.png"))); // NOI18N
        BotonDihatsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDihatsuActionPerformed(evt);
            }
        });

        gestionarModelosToyotaBoton.setBackground(new java.awt.Color(209, 37, 29));
        gestionarModelosToyotaBoton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        gestionarModelosToyotaBoton.setForeground(new java.awt.Color(255, 255, 255));
        gestionarModelosToyotaBoton.setText("Crear  Modelos");
        gestionarModelosToyotaBoton.setToolTipText("");
        gestionarModelosToyotaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarModelosToyotaBotonActionPerformed(evt);
            }
        });

        BotonNissan.setBackground(new java.awt.Color(255, 255, 255));
        BotonNissan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconnissan.jpg"))); // NOI18N
        BotonNissan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNissanActionPerformed(evt);
            }
        });

        gestionarModelosMitsubishiBoton.setBackground(new java.awt.Color(209, 37, 29));
        gestionarModelosMitsubishiBoton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        gestionarModelosMitsubishiBoton.setForeground(new java.awt.Color(255, 255, 255));
        gestionarModelosMitsubishiBoton.setText("Crear  Modelos");
        gestionarModelosMitsubishiBoton.setToolTipText("");
        gestionarModelosMitsubishiBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarModelosMitsubishiBotonActionPerformed(evt);
            }
        });

        gestionarModelosDaihatsuBoton.setBackground(new java.awt.Color(209, 37, 29));
        gestionarModelosDaihatsuBoton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        gestionarModelosDaihatsuBoton.setForeground(new java.awt.Color(255, 255, 255));
        gestionarModelosDaihatsuBoton.setText("Crear  Modelos");
        gestionarModelosDaihatsuBoton.setToolTipText("");
        gestionarModelosDaihatsuBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarModelosDaihatsuBotonActionPerformed(evt);
            }
        });

        modeloXRepuestoBoton.setBackground(new java.awt.Color(209, 37, 29));
        modeloXRepuestoBoton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        modeloXRepuestoBoton.setForeground(new java.awt.Color(255, 255, 255));
        modeloXRepuestoBoton.setText("Crear Repuestos x Modelos");
        modeloXRepuestoBoton.setToolTipText("");
        modeloXRepuestoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloXRepuestoBotonActionPerformed(evt);
            }
        });

        gestionarModelosNissanBoton.setBackground(new java.awt.Color(209, 37, 29));
        gestionarModelosNissanBoton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        gestionarModelosNissanBoton.setForeground(new java.awt.Color(255, 255, 255));
        gestionarModelosNissanBoton.setText("Crear  Modelos");
        gestionarModelosNissanBoton.setToolTipText("");
        gestionarModelosNissanBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarModelosNissanBotonActionPerformed(evt);
            }
        });

        gestionarRepuestosBoton.setBackground(new java.awt.Color(209, 37, 29));
        gestionarRepuestosBoton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        gestionarRepuestosBoton.setForeground(new java.awt.Color(255, 255, 255));
        gestionarRepuestosBoton.setText("Crear Repuestos");
        gestionarRepuestosBoton.setToolTipText("");
        gestionarRepuestosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarRepuestosBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BotonToyota, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonMitsubitshi, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(gestionarModelosToyotaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(gestionarModelosMitsubishiBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonDihatsu, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(gestionarModelosDaihatsuBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonNissan, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(gestionarModelosNissanBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(gestionarRepuestosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modeloXRepuestoBoton)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonNissan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonDihatsu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMitsubitshi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonToyota, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gestionarModelosMitsubishiBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gestionarModelosToyotaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gestionarModelosDaihatsuBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(gestionarModelosNissanBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloXRepuestoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestionarRepuestosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        MnuSalir.setText("Salir");
        MnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(MnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(541, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(434, 434, 434))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(659, 659, 659))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_MnuSalirMouseClicked

    private void BotonToyotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonToyotaActionPerformed
        TBLMarcaVo marcas = controller.marcasCarros(MarcasCarros.TOYOTA.getId());
        JFrame frm = new FrmListarModelosxRepuestos(marcas);
        frm.setLocationRelativeTo(null);
        frm.setResizable(false);
        frm.setVisible(true); 
       
    }//GEN-LAST:event_BotonToyotaActionPerformed

    
    private void BotonMitsubitshiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMitsubitshiActionPerformed
        TBLMarcaVo marcas = controller.marcasCarros(MarcasCarros.MITSUBISHI.getId());
        JFrame frm = new FrmListarModelosxRepuestos(marcas);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true); 
    }//GEN-LAST:event_BotonMitsubitshiActionPerformed

    private void BotonDihatsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDihatsuActionPerformed
      TBLMarcaVo marcas = controller.marcasCarros(MarcasCarros.DAIHATSU.getId());
        JFrame frm = new FrmListarModelosxRepuestos(marcas);
        frm.setLocationRelativeTo(null);
        frm.setResizable(false);
        frm.setVisible(true); 
    }//GEN-LAST:event_BotonDihatsuActionPerformed

    private void gestionarModelosToyotaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarModelosToyotaBotonActionPerformed
        TBLMarcaVo marcas = controller.marcasCarros(MarcasCarros.TOYOTA.getId());
        JFrame frm = new FrmCrearModeloCarrro(marcas);
        frm.setLocationRelativeTo(null);
        frm.setResizable(false);
        frm.setVisible(true);
    }//GEN-LAST:event_gestionarModelosToyotaBotonActionPerformed

    
    private void BotonNissanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNissanActionPerformed
       TBLMarcaVo marcas = controller.marcasCarros(MarcasCarros.NISSAN.getId());
        JFrame frm = new FrmListarModelosxRepuestos(marcas);
        frm.setLocationRelativeTo(null);
        frm.setResizable(false);
        frm.setVisible(true); 
    }//GEN-LAST:event_BotonNissanActionPerformed

    private void gestionarModelosMitsubishiBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarModelosMitsubishiBotonActionPerformed
        TBLMarcaVo marcas = controller.marcasCarros(MarcasCarros.MITSUBISHI.getId());
        JFrame frm = new FrmCrearModeloCarrro(marcas);
        frm.setLocationRelativeTo(null);
        frm.setResizable(false);
        frm.setVisible(true);    }//GEN-LAST:event_gestionarModelosMitsubishiBotonActionPerformed

    private void gestionarModelosDaihatsuBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarModelosDaihatsuBotonActionPerformed
        TBLMarcaVo marcas = controller.marcasCarros(MarcasCarros.DAIHATSU.getId());
        JFrame frm = new FrmCrearModeloCarrro(marcas);
        frm.setLocationRelativeTo(null);
        frm.setResizable(false);
        frm.setVisible(true);   

    }//GEN-LAST:event_gestionarModelosDaihatsuBotonActionPerformed

    private void modeloXRepuestoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloXRepuestoBotonActionPerformed
         //TBLMarcaVo marcas = controller.marcasCarros(MarcasCarros.DAIHATSU.getId());
        JFrame frm = new FrmCrearRepuestoxRepuestoCarro();
        frm.setLocationRelativeTo(null);
        frm.setResizable(false);
        frm.setVisible(true); 
    }//GEN-LAST:event_modeloXRepuestoBotonActionPerformed

    private void gestionarModelosNissanBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarModelosNissanBotonActionPerformed
       TBLMarcaVo marcas = controller.marcasCarros(MarcasCarros.NISSAN.getId());
        JFrame frm = new FrmCrearModeloCarrro(marcas);
        frm.setLocationRelativeTo(null);
        frm.setResizable(false);
        frm.setVisible(true);  

    }//GEN-LAST:event_gestionarModelosNissanBotonActionPerformed

    private void gestionarRepuestosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarRepuestosBotonActionPerformed
        JFrame frm = new FrmCrearRepuestoCarro();
        frm.setLocationRelativeTo(null);
        frm.setResizable(false);
        frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_gestionarRepuestosBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearModeloCarrro(new TBLMarcaVo()).setVisible(true);
            }
        });
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDihatsu;
    private javax.swing.JButton BotonMitsubitshi;
    private javax.swing.JButton BotonNissan;
    private javax.swing.JButton BotonToyota;
    private javax.swing.JMenu MnuSalir;
    public javax.swing.JButton gestionarModelosDaihatsuBoton;
    public javax.swing.JButton gestionarModelosMitsubishiBoton;
    public javax.swing.JButton gestionarModelosNissanBoton;
    public javax.swing.JButton gestionarModelosToyotaBoton;
    private javax.swing.JButton gestionarRepuestosBoton;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modeloXRepuestoBoton;
    // End of variables declaration//GEN-END:variables
}
