CREATE TABLE TBL_REPUESTO(
ID_REPUESTO INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
REFERENCIA VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(600) NULL DEFAULT NULL,
RUTA_IMAGEN VARCHAR(50) NOT NULL,
ID_MODELO INT NOT NULL,
PRIMARY KEY (ID_REPUESTO),
CONSTRAINT ID_MODELO_FK FOREIGN KEY (ID_MODELO) REFERENCES TBL_MODELO(ID_MODELO) on delete cascade on update CASCADE,
INDEX NOMBRE_INDEX (NOMBRE),
INDEX REFERENCIA_INDEX (REFERENCIA),
INDEX DESCRIPCION_INDEX (DESCRIPCION)
);


CREATE TABLE TBL_TIPO_COMBUSTIBLE(
ID_TIPO_COMBUSTIBLE INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(600) NULL DEFAULT NULL,
PRIMARY KEY (ID_TIPO_COMBUSTIBLE),
INDEX ID_MARCA_INDEX (ID_TIPO_COMBUSTIBLE),
INDEX NOMBRE_INDEX (NOMBRE)
);


CREATE TABLE TBL_MODELO(
ID_MODELO INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
ANO VARCHAR(10) NOT NULL,
CILINDRAJE VARCHAR(100) NOT NULL,
ID_TIPO_COMBUSTIBLE INT NOT NULL,
DESCRIPCION VARCHAR(600) NULL DEFAULT NULL,
RUTA_IMAGEN VARCHAR(50) NOT NULL,
ID_REPUESTO INT NOT NULL,
ID_MARCA INT NOT NULL,
PRIMARY KEY (ID_MODELO),
INDEX ID_TIPO_COMBUSTIBLE_INDEX (ID_TIPO_COMBUSTIBLE),
INDEX NOMBRE_INDEX (NOMBRE),
INDEX ANO_INDEX (ANO),
INDEX CILINDRAJE_INDEX (CILINDRAJE),
INDEX DESCRIPCION_INDEX (DESCRIPCION)
);
TBL_MARCA


CREATE TABLE `TBL_MARCA` (
	`ID_MARCA` INT(10) NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(100) NOT NULL COLLATE 'utf8_general_ci',
	`DESCRIPCION` VARCHAR(600) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`ID_MARCA`) USING BTREE,
	INDEX `ID_MODELO_FK` (`ID_MODELO`) USING BTREE,
	INDEX `ID_MARCA_INDEX` (`ID_MARCA`) USING BTREE,
	INDEX `NOMBRE_INDEX` (`NOMBRE`) USING BTREE
);


ALTER TABLE TBL_REPUESTO
ADD ID_MODELO INT NOT NULL;

ALTER TABLE `TBL_MODELO`
ADD CONSTRAINT  ID_TIPO_COMBUSTIBLE_FK FOREIGN KEY (ID_TIPO_COMBUSTIBLE) REFERENCES TBL_TIPO_COMBUSTIBLE(ID_TIPO_COMBUSTIBLE) on delete cascade on update cascade,
ADD CONSTRAINT  ID_MARCA_FK FOREIGN KEY (ID_MARCA) REFERENCES TBL_MARCA(ID_MARCA);


ALTER TABLE `TBL_REPUESTO`
ADD CONSTRAINT `ID_MODELO_FK` FOREIGN KEY (`ID_MODELO`) REFERENCES `repuestos`.`TBL_MODELO` (`ID_MODELO`) on delete cascade on update CASCADE;
 


INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Gasolina','combustible derivado del petróleo por destilación fraccionada');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Etanol','se utiliza para motores de combustión interna alternativa que produce la ignición del combustible en temperaturas altas por su comprensión');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Gasolina','se obtiene de la fermentación de azucares de distintas plantas, como pueden ser la cebada');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Hidrógeno','usado en motores de combustión interna de forma alternativa');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Biodiesel','combustible que es obtenido por lípidos naturales que pueden ser aceites vegetales o incluso grasas animales.');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Electricidad','estos tipos de vehículos usarán uno o varios motores, utilizando la energía almacenada en baterías recargables');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Metanol','alcohol destilado en seco de la madera, que se puede mezclar con la gasolina');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Gas natural','es un combustible formado por mezcla de gases naturales');


DROP TABLE TBL_REPUESTO;
DROP TABLE TBL_TIPO_COMBUSTIBLE;
DROP TABLE TBL_MARCA;
DROP TABLE TBL_MODELO; 

