CREATE TABLE TBL_MARCA(
ID_MARCA INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(600) NULL DEFAULT NULL,
RUTA_IMAGEN VARCHAR(50) NOT NULL,
ESTADO BOOLEAN DEFAULT FALSE,
ID_MODELO INT(11) NOT NULL,
PRIMARY KEY (ID_MARCA),
CONSTRAINT  ID_MODELO_FK FOREIGN KEY (ID_MODELO) REFERENCES TBL_MODELO(ID_MODELO),
INDEX ID_MARCA_INDEX (ID_MARCA),
INDEX NOMBRE_INDEX (NOMBRE),
INDEX CODIGO_INDEX (CODIGO)
);

CREATE TABLE TBL_MODELO(
ID_MODELO INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(600) NULL DEFAULT NULL,
RUTA_IMAGEN VARCHAR(50) NOT NULL,
ESTADO BOOLEAN DEFAULT FALSE,
FECHA_MODELO DATE NOT NULL,
PRIMARY KEY (ID_MODELO),
INDEX ID_MARCA_INDEX (ID_MODELO),
INDEX NOMBRE_INDEX (NOMBRE)
);

CREATE TABLE TBL_REPUESTO(
ID_REPUESTO INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(600) NULL DEFAULT NULL,
RUTA_IMAGEN VARCHAR(50) NOT NULL,
ESTADO BOOLEAN DEFAULT FALSE,
FECHA_REPUESTO DATE NOT NULL,
COLOR VARCHAR(50) NOT NULL,
REFERENCIA VARCHAR(100) NOT NULL,
ID_MARCA INT NOT NULL,
PRIMARY KEY (ID_REPUESTO),
CONSTRAINT  ID_MARCA_FK FOREIGN KEY (ID_MARCA) REFERENCES TBL_MARCA(ID_MARCA),
INDEX ID_MARCA_INDEX (ID_REPUESTO),
INDEX NOMBRE_INDEX (NOMBRE)
);

DROP TABLE TBL_MARCA
SELECT * FROM TBL_MARCA