CREATE TABLE TBL_REPUESTO(
ID_REPUESTO INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
REFERENCIA VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(600) NULL DEFAULT NULL,
RUTA_IMAGEN VARCHAR(600) NOT NULL,
PRIMARY KEY (ID_REPUESTO),
INDEX NOMBRE_INDEX (NOMBRE),
INDEX REFERENCIA_INDEX (REFERENCIA),
INDEX DESCRIPCION_INDEX (DESCRIPCION)
);


CREATE TABLE TBL_TIPO_COMBUSTIBLE(
ID_TIPO_COMBUSTIBLE INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(600) NULL DEFAULT NULL,
PRIMARY KEY (ID_TIPO_COMBUSTIBLE),
INDEX ID_MARCA_INDEX (ID_TIPO_COMBUSTIBLE),
INDEX NOMBRE_INDEX (NOMBRE)
);


CREATE TABLE TBL_MODELO(
ID_MODELO INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
ANO VARCHAR(10) NOT NULL,
CILINDRAJE VARCHAR(100) NOT NULL,
ID_TIPO_COMBUSTIBLE INT NOT NULL,
DESCRIPCION VARCHAR(600) NULL DEFAULT NULL,
RUTA_IMAGEN VARCHAR(600) NOT NULL,
ID_MARCA INT NOT NULL,
PRIMARY KEY (ID_MODELO),
INDEX ID_TIPO_COMBUSTIBLE_INDEX (ID_TIPO_COMBUSTIBLE),
INDEX NOMBRE_INDEX (NOMBRE),
INDEX ANO_INDEX (ANO),
INDEX CILINDRAJE_INDEX (CILINDRAJE),
INDEX DESCRIPCION_INDEX (DESCRIPCION)
);


CREATE TABLE TBL_REPUESTO_X_MODELO(
ID_REPUESTO_X_MODELO INT NOT NULL AUTO_INCREMENT,
ID_REPUESTO INT NOT NULL,
ID_MODELO INT NOT NULL,
PRIMARY KEY (ID_REPUESTO_X_MODELO),
INDEX ID_REPUESTO_INDEX(ID_REPUESTO),
INDEX ID_MODELO_INDEX(ID_MODELO)
);

CREATE TABLE `TBL_MARCA` (
	`ID_MARCA` INT(10) NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(100) NOT NULL COLLATE 'utf8_general_ci',
	`DESCRIPCION` VARCHAR(600) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`ID_MARCA`) USING BTREE,
	INDEX `ID_MARCA_INDEX` (`ID_MARCA`) USING BTREE,
	INDEX `NOMBRE_INDEX` (`NOMBRE`) USING BTREE
);


CREATE TABLE `TBL_SESSION` (
	`ID_SESION` INT(10) NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(100) NOT NULL COLLATE 'utf8_general_ci',
	`DESCRIPCION` VARCHAR(600) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`ID_SESION`) USING BTREE,
	INDEX `NOMBRE_INDEX` (`NOMBRE`) USING BTREE
);


ALTER TABLE `TBL_MODELO`
ADD CONSTRAINT  ID_TIPO_COMBUSTIBLE_FK FOREIGN KEY (ID_TIPO_COMBUSTIBLE) REFERENCES TBL_TIPO_COMBUSTIBLE(ID_TIPO_COMBUSTIBLE),
ADD CONSTRAINT  ID_MARCA_FK FOREIGN KEY (ID_MARCA) REFERENCES TBL_MARCA(ID_MARCA);

ALTER TABLE `TBL_REPUESTO_X_MODELO`
ADD CONSTRAINT  ID_REPUESTO_FK FOREIGN KEY (ID_REPUESTO) REFERENCES TBL_REPUESTO(ID_REPUESTO),
ADD CONSTRAINT  ID_MODELO_FK FOREIGN KEY (ID_MODELO) REFERENCES TBL_MODELO(ID_MODELO); 



INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Gasolina','se obtiene de la fermentación de azucares de distintas plantas, como pueden ser la cebada');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Diesel','combustible que es obtenido por lípidos naturales que pueden ser aceites vegetales o incluso grasas animales.');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Electricidad','estos tipos de vehículos usarán uno o varios motores, utilizando la energía almacenada en baterías recargables');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Hibrido','alcohol destilado en seco de la madera, que se puede mezclar con la gasolina');
INSERT INTO TBL_TIPO_COMBUSTIBLE(NOMBRE,DESCRIPCION)VALUES('Gas natural','es un combustible formado por mezcla de gases naturales');

INSERT INTO TBL_MARCA(NOMBRE,DESCRIPCION)VALUES('Toyota','Toyota');
INSERT INTO TBL_MARCA(NOMBRE,DESCRIPCION)VALUES('Mitsubishi','Mitsubishi');
INSERT INTO TBL_MARCA(NOMBRE,DESCRIPCION)VALUES('Nissan','Nissan');
INSERT INTO TBL_MARCA(NOMBRE,DESCRIPCION)VALUES('Daihatsu','Daihatsu');




INSERT INTO TBL_SESSION(NOMBRE,DESCRIPCION)VALUES('Elias','user session')
INSERT INTO TBL_SESSION(NOMBRE,DESCRIPCION)VALUES('admin','user session')

INSERT INTO TBL_SESSION(NOMBRE,DESCRIPCION)VALUES('GUEST','user session')
INSERT INTO TBL_SESSION(NOMBRE,DESCRIPCION)VALUES('guest','user session')
INSERT INTO TBL_SESSION(NOMBRE,DESCRIPCION)VALUES('USUARIO','user session')
INSERT INTO TBL_SESSION(NOMBRE,DESCRIPCION)VALUES('lenovo','user session')
INSERT INTO TBL_SESSION(NOMBRE,DESCRIPCION)VALUES('User','user session')

DELETE FROM TBL_REPUESTO;
DELETE FROM TBL_MODELO;

DROP TABLE TBL_REPUESTO;
DROP TABLE TBL_TIPO_COMBUSTIBLE;
DROP TABLE TBL_MODELO; 
DROP TABLE TBL_MARCA;
DROP TABLE TBL_REPUESTO_X_MODELO;


SELECT * FROM TBL_MODELO;
SELECT * FROM TBL_REPUESTO;
SELECT * FROM tbl_repuesto_x_modelo;

SELECT * FROM tbl_repuesto_x_modelo rm  WHERE rm.ID_MODELO = ? AND rm.ID_REPUESTO = ?

SELECT * FROM TBL_REPUESTO_X_MODELO rm JOIN  tbl_modelo  md ON rm.ID_MODELO = md.ID_MODELO JOIN tbl_repuesto rp ON rp.ID_REPUESTO = rm.ID_REPUESTO WHERE md.ID_MARCA = 2



INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('PISTONES ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('ANILLOS ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('CASQUETES ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('1/2 LUNAS ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BUJES DE BIELA  ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BUJES DE LEVAS  ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('GUIAS DE VALVULAS  ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('VALVULAS ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('EMPAQUETADURA DE MOTOR  ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('KIT DE REPARTICION ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('SOPORTES DE MOTOR  ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('EJE DE LEVAS  ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BOMBA DE ACEITE ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('FILTRO DE ACEITE ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BOMBA DE AGUA ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('FILTRO DE AIRE  ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BOMBA DE GASOLINA ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('KIT DE CLUTCH ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('PASTILLAS DE FRENO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BANDAS DE FRENO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BOBINAS DE ENCENDIDO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BUJIAS ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BIELA DE MOTOR ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('KIT DE CLUTCH ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BOMBA PRINCIPAL DE CLUTCH ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BOMBA AUXILIAR DE CLUTCH ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('RODAMIENTO RUEDA DELANTERO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('RODAMIENTO RUEDA TRASERO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('CAJA DE DIRECCION ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('AMORTIGUADOR DELANTERO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('AMORTIGUADOR TRASERO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('AMORTIGUADOR DE DIRECCION ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('TIJERA SUPERIOR ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('TIJERA INFERIOR ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BUJES DE TIJERA INFERIOR ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BUJE TIJERA SUPERIOR ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BUJE ESTABILIZADORA ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BUJES DE TEMPLETE ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('MUÑECOS ESTABILIZADORA ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('SOPORTES DE AMORTIGUADOR ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('GUAYA DE FRENO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('GUAYA DE CLUTCH ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BOOSTER DE FRENO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('PRENSA DE CLUTCH ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('DISCO DE CLUTCH ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BALINERA DE CLUTCH ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('DISCO DE FRENO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('SENSOR DE TEMPERATURA ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('TERMOSTATO ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('SENSOR O PERA DE ACEITE ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('FILTRO DE GASOLINA ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('FILTRO DE COMBUSTIBLE ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('IMPULSADORES ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('BALANCINES DE MOTOR  ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');
INSERT INTO TBL_REPUESTO (NOMBRE,REFERENCIA,DESCRIPCION,RUTA_IMAGEN) VALUES('FLAUTA DE MOTOR ','REFERENCIA','DESCRIPCION','RUTA_IMAGEN');